---

- name: check first run
  set_fact:
    app_first_run: True
  when: ansible_local[app_name] is not defined
  ignore_errors: yes

- block:
    - name: determine current color
      set_fact:
        _current_color: "{{ ansible_local[app_name][app_name].env_color }}"

    - name: determine current count of instances
      set_fact:
        _current_count: "{{ ansible_local[app_name][app_name].instances_count }}"

    - name: determine current version
      set_fact:
        _current_version: "{{ ansible_local[app_name][app_name].version }}"
  when: not app_first_run

- block:
    - name: set current color if not in facts
      set_fact:
        _current_color: "{{ app_default_color }}"

    - name: determine current count of instances if not in facts
      set_fact:
        _current_count: "{{ app_instances_count }}"
  when: app_first_run

- name: set new color
  set_fact:
    _next_color: "blue"
  when: _current_color == "green"

- name: set new color
  set_fact:
    _next_color: "green"
  when: _current_color == "blue"

- name: don't change color if deploying same version
  set_fact:
    _next_color: "{{ _current_color }}"
  when:
    - not app_first_run
    - _current_version == app_version

- name: set port_prefix for blue
  set_fact:
    app_port_prefix: "{{ app_port_prefix_blue }}"
  when: _next_color == "blue"

- name: set port_prefix for green
  set_fact:
    app_port_prefix: "{{ app_port_prefix_green }}"
  when: _next_color == "green"
