- name: run the playbook tasks on the localhost
  hosts: local
  vars:
    app_name: demo
    repo_url: https://github.com/lsioctl/demo
    repo_remote: origin
    repo_version: master
    webapps_dir: /app
  tasks:

  - name: create future prod container
    docker_container:
      name: prod 
      image: tiangolo/uwsgi-nginx-flask:python3.7
      published_ports: 8081:80
      volumes: prod-data:/var/data
  
  - name: add container to inventory
    add_host:
      name: prod 
      ansible_connection: docker
      ansible_user: root 
    changed_when: false
  
  - name: git pull project 
    delegate_to: prod
    git: repo={{repo_url}} dest={{webapps_dir}}/{{app_name}} version={{repo_version}}
