---
- name: check nginx configuration
  delegate_to: cicdinfra_nginx_1
  command: nginx -t -c /etc/nginx/nginx.conf
  register: result
  changed_when: "result.rc != 0"

- debug:
    var: result

- name: reload nginx
  delegate_to: cicdinfra_nginx_1
  service:
    name: nginx
    state: reloaded

- name: make test request
  uri:
    url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}{{ app_health_check_path }}"
    method: GET
    status_code: 200
  when: app_check_health
  tags:
    - app:check

# vim: set et fenc= ft=ansible sts=2 sw=2 ts=2 tw=0 :
